import type { IParser } from '@/types'
import { MIN_PRICE_INR } from '@/constants'

// ─── Flipkart Parser ──────────────────────────────────────────────────────────

/**
 * Parser for Flipkart India (www.flipkart.com).
 *
 * Flipkart uses obfuscated, frequently rotating class names generated by
 * their Webpack build. We therefore use a resilient, multi-strategy approach:
 *
 * Price extraction order (most to least reliable):
 *   1. Stable data-testid / data-id attributes (rarely change)
 *   2. Known class-name fragments via [class*="…"] partial matching
 *   3. Semantic: [class*="price"] within the product container
 *   4. Raw textContent fallback
 *
 * findPriceNodes() strategies:
 *   1. Product Detail Page (PDP) — specific container blocks
 *   2. Search / listing page — one price per product card
 */
export class FlipkartParser implements IParser {
  supports(url: string): boolean {
    return /^https?:\/\/(www\.)?flipkart\.com\//.test(url)
  }

  findPriceNodes(): Element[] {
    const nodes: Element[] = []

    // Strategy 1: Product Detail Page
    const pdpNodes = this.strategy_pdp()
    if (pdpNodes.length > 0) {
      return this.deduplicate(pdpNodes)
    }

    // Strategy 2: Search / listing page
    nodes.push(...this.strategy_listing())

    return this.deduplicate(nodes)
  }

  extractPrice(element: Element): number | null {
    // ── Method 1: data-testid attribute on price span ──
    const testIdEl = element.querySelector('[data-testid*="price"]')
    if (testIdEl?.textContent) {
      const price = this.parseINRString(testIdEl.textContent)
      if (price !== null && price >= MIN_PRICE_INR) return price
    }

    // ── Method 2: Partial class match for known Flipkart price wrappers ──
    // Flipkart's compiled class names historically contain "Nx9bqj", "30jeq3",
    // "_1vC4OE" variants. We match by partial string to stay resilient.
    const partialSelectors = [
      '[class*="Nx9bqj"]',  // current PDP selling price class fragment
      '[class*="30jeq3"]',  // older obfuscated class fragment
      '[class*="1vC4OE"]',  // older class fragment
    ]
    for (const sel of partialSelectors) {
      try {
        const el = element.querySelector(sel) ?? (element.matches(sel) ? element : null)
        if (el?.textContent) {
          const price = this.parseINRString(el.textContent)
          if (price !== null && price >= MIN_PRICE_INR) return price
        }
      } catch {
        // skip invalid selector
      }
    }

    // ── Method 3: Semantic class fragment match on the element itself ──
    const semanticSelectors = ['[class*="price"]', '[class*="Price"]']
    for (const sel of semanticSelectors) {
      try {
        const el = element.querySelector(sel) ?? (element.matches(sel) ? element : null)
        if (el?.textContent) {
          const price = this.parseINRString(el.textContent)
          if (price !== null && price >= MIN_PRICE_INR) return price
        }
      } catch {
        // skip
      }
    }

    // ── Method 4: Raw textContent fallback ──
    const rawText = element.textContent ?? ''
    if (rawText) {
      const price = this.parseINRString(rawText)
      if (price !== null && price >= MIN_PRICE_INR) return price
    }

    return null
  }

  // ─── Strategies ──────────────────────────────────────────────────────────

  private strategy_pdp(): Element[] {
    const selectors = [
      // Stable structural containers on Flipkart PDP
      '._30jeq3',           // historical selling price class
      '.Nx9bqj',            // current selling price class (as of 2024-25)
      '[class*="pdp-price"]',
      '[class*="finalPrice"]',
      '[class*="selling-price"]',
      // ARIA / data attribute based (most stable)
      '[data-testid="dp-price"]',
      '[data-id="selling-price"]',
    ]
    return this.queryAllFirst(selectors)
  }

  private strategy_listing(): Element[] {
    // Flipkart search cards have a stable container
    const cards = document.querySelectorAll(
      '[data-id], ._1AtVbE, [class*="productCard"]'
    )

    if (cards.length > 0) {
      const results: Element[] = []
      cards.forEach((card) => {
        // Take only the first price element per card
        const priceEl =
          card.querySelector('[class*="Nx9bqj"]') ??
          card.querySelector('[class*="30jeq3"]') ??
          card.querySelector('[class*="price"]')
        if (priceEl) results.push(priceEl)
      })
      if (results.length > 0) return results
    }

    // Flat fallback
    return this.queryAllFirst([
      '._30jeq3',
      '.Nx9bqj',
      '[class*="selling-price"]',
    ])
  }

  // ─── Utilities ────────────────────────────────────────────────────────────

  private queryAllFirst(selectors: string[]): Element[] {
    for (const selector of selectors) {
      try {
        const found = [...document.querySelectorAll(selector)]
        if (found.length > 0) return found
      } catch {
        // skip invalid selector
      }
    }
    return []
  }

  private deduplicate(elements: Element[]): Element[] {
    return [...new Set(elements)]
  }

  /**
   * Parses an INR price string into a number.
   * Handles: ₹12,999 · ₹ 12,999.00 · ₹1,23,456 · 12999
   */
  private parseINRString(text: string): number | null {
    const cleaned = text.replace(/[₹,\s]/g, '').trim()
    const match = /^(\d+(?:\.\d{1,2})?)/.exec(cleaned)
    if (!match) return null
    const num = parseFloat(match[1])
    return isNaN(num) ? null : num
  }
}
